stages:
  - prod

prod:
  stage: prod
  image: dapppicnexus1:8082/php:7.2
  when: always
  only:
    - master
  script:
    - project=dba-$(./dba --version | cut -d' ' -f2)
    - archive=/tmp/$project.tar.gz
    - composer install --no-dev
    - cd ../
    - tar czf $archive dba --warning=no-file-changed
    - curl -# -o output -k -L --upload-file $archive -u jenkins:jenkins -X PUT http://nexus-pic.gendarmerie.fr/repository/binaries-stc/dba/
