stages:
  - prod

prod:
  stage: prod
  image: dapppicnexus1:8082/php:7.2
  when: always
  only:
    - master
  script:
    - composer install --production
    - zip -ru ./dba-$(dba --version | cut -d' ' -f2).zip ./
