version: 1.0.0

# temp directory
tmp_dir: "/tmp"

# conf  base targets
targets:

        name_config:
                # the dumper config
                dumper:
                        # PGSQL
                        # dumper class, extends ADumper
                        class: "\\DBA\\Dumpers\\Pgsql"
                        # host target
                        dbhost: "localhost"
                        # port target
                        dbport: "5432"
                        # base name target
                        dbname: "dbname"
                        # base user
                        dbuser: "dbuser"
                        #base password
                        dbpassword: "pwd"


              # compressor default to null
                compressor:
                        # compressor class, dextends ACompressor
                        class: "\\DBA\\Compressors\\Zip"
                       #archiver, put export to
                archiver:
                        # archiver class, extends AArchiver
                        class: "\\DBA\\Archivers\\S3"
                        # endpoint
                        endpoint: "https://s3.amazone.com"
                        # keyname
                        keyname: "keyname id"
                        # secret
                        secret: "secret"
                        #bucket
                        bucket: "bucket name"

