version: '3.4'

services:

#  php:
#    build:
#      context: docker
#      args:
#        PHP_VERSION: ${PHP_VERSION}
#    image: dba:php-${PHP_VERSION}
#    working_dir: /var/www
#    volumes:
#      - ./:/var/www/
#      - ./docker/30-dba.ini:/usr/local/etc/php/conf.d/30-dba.ini


  php:
    image: ${DOCKER_REGISTRY}php
    working_dir: /var/www
    volumes:
      - ./:/var/www/

  mysql:
    image: ${DOCKER_REGISTRY}mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dba'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sic'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'sic'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'dba'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - dba-vol:/var/lib/mysql
# Names our volume

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - 'mysql'
    environment:
      PMA_HOST: 'db'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  database:
    image: '${DOCKER_REGISTRY}mongo'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=db
      - MONGO_INITDB_ROOT_USERNAME=dba
      - MONGO_INITDB_ROOT_PASSWORD=dba
    volumes:
      - ./var/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./var/mongo-volume:/data/db
    ports:
      - '27017:27017'



volumes:
  dba-vol: